var milestones = [
    'Login Page URL',
    'Login Page Regex',
    'Invalid Creds Regex',
  'Invalid Creds Regex 2 [Optional]',
  'Logged in page Regex',
  'Post URL (log-in)',
 'User name field selector [Phantom]',
  'Password field selector [Phantom]',
  'Submit button selector [Phantom]',
  'Account number selector',
  'Account table selector [optional]',
  'Billing Page URL',
 'Billing Page Regex',
  'Billing Table Row selector',
  'Billing Table Data - Amount [optional]',
  'Billing Table Data - Date',
  'Billing Table Row - Bill Link',
  'Billing Table Row - Due Date [optional]',
  'Billing Table Row - Tax [optional]',
  'Billing Table Row - Invoice Number/Custom [optional]',
  'Billing Table Row - Payment Method [optional]',
  'Billing Table Row - Payment Account Number [optional]'
  ]
